"""
Phase 1D — Evidence Chain & Explainable Alert Intelligence Engine (SIH26127)
-----------------------------------------------------------------------------
Constructs transparent, auditable, human-readable evidence records for all
detected anomalies. Answers the 5 Ws: WHAT, WHERE, WHEN, WHY, and WHAT TO REVIEW.

Maintains strict separation between OBSERVED camera sightings and PREDICTED next-route estimates.

================================================================================
HOW TO RUN THIS MODULE:
================================================================================
python backend/src/evidence_chain.py
================================================================================
"""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import List, Dict, Any, Optional

# Ensure module directory is in sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))


class EvidenceChainEngine:
    def __init__(self):
        """
        Initialize Evidence Chain Engine.
        """
        pass

    def build_evidence_record(
        self,
        anomaly_item: Dict[str, Any],
        trajectory_info: Optional[Dict[str, Any]] = None,
        prediction_info: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Build an explainable, auditable evidence record for a single anomaly.

        :param anomaly_item: Anomaly record generated by AnomalyRadarEngine.
        :param trajectory_info: Optional trajectory data for vehicle.
        :param prediction_info: Optional prediction data from RoutePredictorEngine.
        :return: Structured evidence chain record.
        """
        identity = anomaly_item.get("fused_identity") or "UNKNOWN_VEHICLE"
        atype = anomaly_item.get("anomaly_type") or "UNEXPECTED_ROUTE"
        severity = anomaly_item.get("severity") or "MEDIUM"
        score = anomaly_item.get("anomaly_score", 0)

        cam_from = anomaly_item.get("camera_from") or "Unavailable"
        cam_to = anomaly_item.get("camera_to") or "Unavailable"

        t_from = anomaly_item.get("timestamp_from") or "Unavailable"
        t_to = anomaly_item.get("timestamp_to") or "Unavailable"

        raw_ev = anomaly_item.get("evidence", {})

        # Extract trajectory evidence
        route = trajectory_info.get("camera_sequence") if trajectory_info else [cam_from, cam_to]
        dt = raw_ev.get("time_diff_seconds")
        dist_km = raw_ev.get("distance_km")
        speed_kmh = raw_ev.get("calculated_speed_kmh")

        # Extract OCR values & confidences if present
        source_ocr = raw_ev.get("original_ocr_source") or raw_ev.get("normalized_values", {}).get("source") or identity
        dest_ocr = raw_ev.get("original_ocr_destination") or raw_ev.get("normalized_values", {}).get("destination") or identity

        source_ocr_conf = raw_ev.get("ocr_confidence", {}).get("source") if isinstance(raw_ev.get("ocr_confidence"), dict) else None
        dest_ocr_conf = raw_ev.get("ocr_confidence", {}).get("destination") if isinstance(raw_ev.get("ocr_confidence"), dict) else None

        # Extract Prediction Evidence (explicitly status-marked as PREDICTED)
        pred_next_cam = None
        pred_prob = None
        if prediction_info:
            pred_next_cam = prediction_info.get("predicted_next_camera")
            top_preds = prediction_info.get("predictions", [])
            if top_preds and len(top_preds) > 0:
                pred_prob = top_preds[0].get("probability")

        # -----------------------------------------------------------------
        # Construct Explanation & 5 Ws Summary
        # -----------------------------------------------------------------
        primary_reason = anomaly_item.get("reason") or f"Anomaly {atype} detected for {identity}."
        supporting_factors: List[str] = []

        if atype == "IMPOSSIBLE_TRANSITION":
            if dt is not None:
                supporting_factors.append(f"Observed travel time delta between {cam_from} and {cam_to} was {dt:.1f}s")
            if speed_kmh is not None:
                supporting_factors.append(f"Calculated travel speed {speed_kmh:.1f} km/h exceeds physical limit")
            if raw_ev.get("implied_behavior"):
                supporting_factors.append(f"Implied physical violation: {raw_ev['implied_behavior']}")

        elif atype == "UNEXPECTED_ROUTE":
            expected = raw_ev.get("expected_next_nodes")
            if expected:
                supporting_factors.append(f"Configured topology expected next nodes from {cam_from}: {', '.join(expected)}")
            supporting_factors.append(f"Observed transition to {cam_to} is outside allowed corridors")
            if dt is not None:
                supporting_factors.append(f"Observed travel time delta was {dt:.1f}s")

        elif atype == "TEMPORAL_ANOMALY":
            if dt is not None:
                supporting_factors.append(f"Observed time gap between sightings: {dt/60.0:.1f} minutes ({dt:.1f}s)")
            max_win = raw_ev.get("max_expected_window_seconds", 1800)
            supporting_factors.append(f"Configured maximum expected travel window: {max_win/60.0:.0f} minutes")

        elif atype == "IDENTITY_CONFLICT":
            supporting_factors.append(f"Conflicting simultaneous sightings recorded at nodes {cam_from} and {cam_to}")
            if dt is not None:
                supporting_factors.append(f"Sightings occurred within {abs(dt):.1f}s delta")
            f_conf = raw_ev.get("fused_confidence")
            if f_conf:
                supporting_factors.append(f"Phase 1A fused identity match confidence: {f_conf}")

        # Construct 5 Ws summary
        five_ws = {
            "what": f"{atype.replace('_', ' ')} detected for vehicle {identity} (Score: {score}/100, Severity: {severity})",
            "where": f"Camera node transition: {cam_from} -> {cam_to}",
            "when": f"From {t_from} to {t_to} (Delta: {dt:.1f}s)" if dt is not None else f"From {t_from} to {t_to}",
            "why": primary_reason,
            "review_guidance": "Verify camera feed logs, inspect OCR plate bounding boxes, and confirm vehicle location.",
        }

        # Deterministic human-readable explanation text
        explanation_text = f"Vehicle {identity} was observed at {cam_from} and {cam_to}."
        if dt is not None:
            explanation_text += f" Time delta was {dt:.1f}s."
        explanation_text += f" {primary_reason} Manual review recommended."

        evidence_id = f"EV-{atype[:4]}-{abs(hash(identity + str(t_from) + str(cam_from))) % 100000:05d}"

        record = {
            "evidence_id": evidence_id,
            "fused_identity": identity,
            "anomaly_type": atype,
            "severity": severity,
            "anomaly_score": score,
            "status": "REQUIRES_REVIEW" if anomaly_item.get("recommended_review", True) else "INFO_ONLY",

            "source": {
                "camera_id": cam_from,
                "timestamp": t_from,
                "ocr_value": source_ocr,
                "ocr_confidence": source_ocr_conf,
            },

            "destination": {
                "camera_id": cam_to,
                "timestamp": t_to,
                "ocr_value": dest_ocr,
                "ocr_confidence": dest_ocr_conf,
            },

            "trajectory_evidence": {
                "route": route,
                "time_gap_seconds": dt,
                "distance_km": dist_km,
                "calculated_speed_kmh": speed_kmh,
            },

            "prediction_evidence": {
                "predicted_next_camera": pred_next_cam,
                "prediction_probability": pred_prob,
                "status": "PREDICTED",
                "disclaimer": "Predicted estimates are probabilistic and distinct from confirmed observed camera sightings.",
            },

            "explanation": {
                "primary_reason": primary_reason,
                "supporting_factors": supporting_factors,
                "summary_text": explanation_text,
                "five_w_summary": five_ws,
                "confidence": round(float(score or 0) / 100.0, 2),
            },

            "recommended_action": "MANUAL_REVIEW" if anomaly_item.get("recommended_review", True) else "LOG_ONLY",
        }
        return record

    def build_evidence_chain(
        self,
        anomaly_radar_output: Dict[str, Any],
        reconstructed_trajectories: Optional[Dict[str, Any]] = None,
        predictions_output: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Build complete Evidence Chain array for all detected anomalies.
        """
        evidence_chain = []
        anomalies = anomaly_radar_output.get("anomaly_records", [])
        trajectories = reconstructed_trajectories or {}
        preds_map = (predictions_output or {}).get("predictions", {})

        for a in anomalies:
            identity = a.get("fused_identity")
            traj_info = trajectories.get(identity) if identity else None
            pred_info = preds_map.get(identity) if identity else None
            ev_record = self.build_evidence_record(a, traj_info, pred_info)
            evidence_chain.append(ev_record)

        return evidence_chain


def main():
    parser = argparse.ArgumentParser(
        description="SIH26127 - Phase 1D Evidence Chain Engine."
    )
    parser.add_argument(
        "--report",
        type=str,
        default="backend/data/analytics_report.json",
        help="Path to analytics report JSON file.",
    )
    args = parser.parse_args()

    if os.path.exists(args.report):
        with open(args.report, "r") as f:
            data = json.load(f)
        anom_data = data.get("anomaly_radar", {})
        traj_data = data.get("reconstructed_trajectories", {})
        pred_data = data.get("predictive_route_intelligence", {})
    else:
        print(f"[WARNING] File not found: '{args.report}'. Running demo evidence chain scan.")
        anom_data = {"anomaly_records": []}
        traj_data = {}
        pred_data = {}

    engine = EvidenceChainEngine()
    chain = engine.build_evidence_chain(anom_data, traj_data, pred_data)

    print("\n================================================================================")
    print("                    PHASE 1D EVIDENCE CHAIN SUMMARY                             ")
    print("================================================================================")
    print(f"Total Evidence Records Generated : {len(chain)}")
    print("--------------------------------------------------------------------------------")
    for idx, item in enumerate(chain, 1):
        print(f"[{idx}] Evidence ID: {item['evidence_id']} | Anomaly: {item['anomaly_type']} ({item['severity']})")
        print(f"    Identity: {item['fused_identity']} | Node Transition: {item['source']['camera_id']} -> {item['destination']['camera_id']}")
        print(f"    5 Ws What: {item['explanation']['five_w_summary']['what']}")
        print(f"    Why      : {item['explanation']['primary_reason']}")
        print(f"    Action   : {item['recommended_action']}")
    print("================================================================================\n")


if __name__ == "__main__":
    main()
